config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
  validates :content,    length: { in: 1..140 }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create, :edit, :update, :destroy]

  def create
    @comment = @post.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        flash.now[:notice] = 'コメントが投稿されました'
        format.js { render :index }
      else
        flash.now[:notice] = '文字数は1文字以上150文字以内にしてください'
        format.js { render :error }
      end
    end
  end

  def edit
    @comment = @post.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    @comment = @post.comments.find(params[:id])
      respond_to do |format|
        if @comment.update(comment_params)
          flash.now[:notice] = 'コメントが編集されました'
          format.js { render :index }
        else
          flash.now[:notice] = '文字数は1文字以上150文字以内にしてください'
          format.js { render :edit_error }
        end
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
      @comment.destroy
      respond_to do |format|
        flash.now[:notice] = 'コメントが削除されました'
        format.js { render :index }
      end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @comments = @post.comments
    @comment = @post.comments.build
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_edit.html.erb
<%= render 'layouts/flash' %>
<div id="comment_edit_form">
  <%= form_with(model: [post, comment]) do |f| %>
    <div class="input-field">
      <%= f.text_area :content, class: "materialize-textarea", id: "comment_content_#{post.id}" %>
      <%= f.label :content, class: "active" %>
      <%= button_tag :type => "submit", :class =>"btn waves-effect waves-light" do %>
        送信
      <% end %>
      <%= link_to :back, class: "btn white black-text waves-effect waves-light" do %>
        戻る
      <% end %>
    </div>
  <% end %>
</div>

app/views/comments/_edit_error.html.erb
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <%= render 'layouts/flash' %>
    <h5><%= @comment.errors.count %>件のエラーがあります。</h5>
    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/comments/_error.html.erb
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <%= render 'layouts/flash' %>
    <h5><%= @comment.errors.count %>件のエラーがあります。</h5>
    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="comment-form">
  <%= form_with(model: [post, comment]) do |f| %>
    <div class="input-field">
      <%= f.text_area :content, class: "materialize-textarea" %>
      <%= f.label :content, "コメント内容", class: "active" %>
      <span class="helper-text" data-error="wrong" data-success="right">1から140文字以内</span>
    </div>
    <div class="comment-button">
      <%= button_tag :type => "submit", :class =>"waves-effect waves-light btn" do %>
        <%= t('.comment') %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/comments/_index.html.erb
<%= render 'layouts/flash' %>
<hr>
<% comments.order(created_at: :desc).each do |comment| %>
  <% if comment.id.present? %>
    <div class="show-comment show-box" id="comment_<%= comment.id %>">
      <div>
      </div>
      <div id="errors_area_<%= comment.id %>">
        <%= render partial: 'comments/edit_error' %>
      </div>
      <div class="comment-content" id ="this_comment_<%= comment.id %>">
        <%= simple_format(comment.content) %>
      </div>
      <span>投稿日時:<%= time_ago_in_words(comment.created_at) %></span>
        <span class="badge"><%= link_to t('.delete'), post_comment_path(comment.post_id, comment.id), method: :delete, remote: true,
                                        data: { confirm: "本当に削除しますか?"} %></span>
        <span class="badge"><%= link_to t('.edit'), edit_post_comment_path(post, comment), remote: true %></span>

    </div>
    <hr>
  <% end %>
<% end %>

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', post: @post, comment: @comment %>");

app/views/comments/edit_error.js.erb
$("#comments_area").html("<%= j(render 'comments/edit_error', { comments: @comment.post.comments, post: @comment.post }) %>")

app/views/comments/error.js.erb
$("#comments_area").html("<%= j(render 'comments/error', { comments: @comment.post.comments, post: @comment.post }) %>")

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.post.comments, post: @comment.post }) %>")
$("textarea").val('')
$('#error_explanation').remove();

app/views/comments/update.js.erb
$('#comments_area').replaceWith
("<%=j render 'comments/index',post: @post, comment: @comment, comments: @post.comments, remote: true %>");

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleComment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<div id="comments_area">
  <%= render partial: 'comments/index', locals: { comments: @comments, post: @post } %>
</div>
  <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>